[profile.default]
src = "src"
out = "out"
script = "script"
libs = ["lib", "node_modules"]
solc = "0.8.19"
evm_version = "shanghai"
optimizer = true
optimizer_runs = 200
remappings = [
  "@openzeppelin/contracts/=lib/OpenZeppelin/openzeppelin-contracts@4.8.3/contracts/",
  "@openzeppelin/contracts-upgradeable/=lib/OpenZeppelin/openzeppelin-contracts-upgradeable@4.8.3/contracts/",
  "@chainlink/contracts-ccip/=node_modules/@chainlink/contracts-ccip/",
  "@chainlink/local/src/=lib/chainlink-local/src/",
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
